name: Validate Scrapers

on:
  push:
      paths:
      - 'scrapers/**'  
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: cd ./validator && yarn install --frozen-lockfile
    - run: node ./validate.js --ci